volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis:7
    ports:
      - 6379:6379
    env_file:
      - .env

  mailpit:
    image: axllent/mailpit:latest
    env_file:
      - .env
    ports:
      - 8025:8025
      - 1025:1025
